---
- name: Reset password hash from previous iteration
  set_fact:
    user_random_password_hash: ""

- name: "Checking if user '{{ user.username }}' exists"
  ansible.builtin.getent:
    database: passwd
    key: "{{ user.username }}"
  failed_when: false
  changed_when: false

- name: "output getent_passwd"
  ansible.builtin.debug:
    var: ansible_facts.getent_passwd
  when: users_debug | bool

- name: "Generating random password for user '{{ user.username }}'"
  command: "{{ user.random_password_command | default(users_random_password_command) }}"
  register: random_password
  delegate_to: localhost
  become: false
  run_once: false
  changed_when: false
  when: >
    (
      ansible_facts.getent_passwd is not defined or
      user.username not in ansible_facts.getent_passwd
    ) and
    user.random_password | default(users_random_password) | bool

- name: "Hashing password for user '{{ user.username }}'"
  set_fact:
    user_random_password_hash: "{{ random_password.stdout | password_hash('sha512') }}"
  when: random_password is defined and random_password.stdout is defined

- name: "Adding user '{{ user.username }}' to the system"
  ansible.builtin.user:
    name: "{{ user.username }}"
    uid: "{{ user.uid | default(omit) }}"
    home: "{{ user.home | default(users_home ~ '/' ~ user.username ) }}"
    comment: "{{ user.name | default(omit) }}"
    system: "{{ user.system | default(omit) }}"
    generate_ssh_key: "{{ user.ssh_key_generate | default(omit) }}"
    group: "{{
            omit if user.group is defined and user.group == user.username
            else (user.group if user.group is defined else (users_group if users_group else omit))
            }}"
    groups: "{{ user.groups|join(',') if user.groups is defined else users_groups|join(',') }}"
    append: "{{ user.append | default(omit) }}"
    password: "{{ user_random_password_hash if (user_random_password_hash | length > 0) else (user.password | default(omit)) }}"
    ssh_key_file: ".ssh/id_{{ user.ssh_key_type | default(users_ssh_key_type) }}"
    ssh_key_passphrase: "{{ user.ssh_key_password | default(omit) }}"
    ssh_key_bits: "{{ user.ssh_key_bits | default(users_ssh_key_bits) }}"
    createhome: "{{ user.home_create | default(users_home_create) }}"
    shell: "{{ user.shell | default(users_shell | default(omit)) }}"
    update_password: "{{ 'always' if (user_random_password_hash | length > 0) else (user.update_password | default(omit)) }}"
  when: >
    (
      (user.update_user | default(users_update_user)) == "always" or
      (
        (user.update_user | default(users_update_user)) == "on_create" and
        (
          ansible_facts.getent_passwd is not defined or
          user.username not in ansible_facts.getent_passwd
        )
      )
    )
    and (user.user_create | default(users_user_create) | bool)

- name: Only if newly created
  ansible.builtin.debug:
    msg: "User was just created"
  when: >
    users_debug | bool and
    (ansible_facts.getent_passwd is not defined or
    user.username not in ansible_facts.getent_passwd)

- name: Configuring user's home
  import_tasks: manage_user_home.yml
  when: user.home_create | default(users_home_create) | bool

- name: Set last password change date
  ansible.builtin.command:
    cmd: chage -d {{ user.random_password_change_date | default(users_random_password_change_date) }} {{ user.username }}
  changed_when: false
  when: user_random_password_hash | length > 0

- name: Store password in home directory
  copy:
    content: "{{ random_password.stdout }}\n"
    dest: "{{ user.home | default(users_home ~ '/' ~ user.username) }}/password"
    owner: "{{ user.username }}"
    group: "{{ user.username }}"
    mode: '0600'
  become: true
  when: user_random_password_hash | length > 0
